# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9925fcf0d52b35664314c9702561d26f91f21fad4c6f3eadf88b8f19d31aa57ac38418c4877a1cad5721a7c8e634cc15fc57c5193b0ed180d3d4b2c2edd512b

test:
  secret_key_base: 5ffdadcac93b9e249edf8d523e5eb845270cc67366a3186ac651771cebafe62b1bbea23f2bf1116db13500c072e451922d4d58217fffa0bb9bc2fb7ee139680e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
